"""Writes texture_masks.py: which pixels of a picture are solid, for every model shaped after its picture.

The 3D doors and trapdoors give every window real depth, glow lichen, sculk veins, vines (nether ones too), lily pads
and redstone dust get their thickness pixel by pixel, and pointed dripstone's sides may only show pixels
that are solid - so their shape depends on where each picture is see-through. Only that outline is
stored (one "#" or "." per pixel) - never the pictures themselves.
Rerun when a Minecraft update changes one of these pictures:

Usage: python extract_masks.py <client.jar>
"""
import io
import pathlib
import re
import sys
import zipfile

from PIL import Image

OUT = pathlib.Path(__file__).parent / "texture_masks.py"
# Pictures besides the doors' and trapdoors' (those are found from the blockstates)
EXTRA = ["glow_lichen", "sculk_vein", "vine", "weeping_vines", "weeping_vines_plant", "twisting_vines", "twisting_vines_plant", "bush", "firefly_bush", "sweet_berry_bush_stage0", "sweet_berry_bush_stage1", "sweet_berry_bush_stage2", "sweet_berry_bush_stage3", "stonecutter_saw", "calibrated_sculk_sensor_amethyst", "bamboo_stage0", "lily_pad", "redstone_dust_dot", "redstone_dust_line0", "redstone_dust_line1"] + [
    f"pointed_dripstone_{direction}_{thickness}" for direction in ("down", "up")
    for thickness in ("tip", "frustum", "middle", "base", "tip_merge")]
# Pictures whose lighter pixels get a mask of their own ("<name>_light": solid and at least this bright) -
# the vine's leaves stand further out than its stems
LIGHT = {"vine": 131}
# Pictures split into their grey metal pixels ("<name>_metal") and all others ("<name>_wood") - the
# curved rail's rails stand higher than its ties
METAL = ["rail_corner"]
GREY_SPREAD = 12  # a pixel is grey metal when its color channels are this close together


def mask(jar: zipfile.ZipFile, texture: str, brightness: int = 0, metal: bool | None = None) -> list | None:
    """16 rows of '#'/'.' ('#': solid, at least `brightness` bright and - unless `metal` is None - grey
    metal or not) - None when every pixel counts."""
    image = Image.open(io.BytesIO(jar.read(f"assets/minecraft/textures/block/{texture}.png"))).convert("RGBA")
    image = image.crop((0, 0, image.width, image.width)).resize((16, 16), Image.NEAREST)

    def counts(pixel) -> bool:
        grey = max(pixel[:3]) - min(pixel[:3]) < GREY_SPREAD
        return pixel[3] > 0 and max(pixel[:3]) >= brightness and (metal is None or grey == metal)

    rows = ["".join("#" if counts(image.getpixel((x, y))) else "." for x in range(16)) for y in range(16)]
    return None if all(row == "#" * 16 for row in rows) else rows


def main():
    jar = zipfile.ZipFile(sys.argv[1])
    blocks = sorted(
        match.group(1) for name in jar.namelist()
        if (match := re.fullmatch(r"assets/minecraft/blockstates/((?!waxed_)\w+_(?:door|trapdoor))\.json", name))
    )
    textures = []
    for block in blocks:
        textures += [f"{block}_bottom", f"{block}_top"] if block.endswith("_door") else [block]
    textures += EXTRA
    lines = [
        '"""Generated by extract_masks.py - which pixels of each picture are solid ("#").',
        'None: every pixel is solid."""',
        "",
        "MASKS = {",
    ]
    for texture in textures:
        rows = mask(jar, texture)
        lines.append(f'    "{texture}": {None if rows is None else " ".join(rows)!r},')
    for texture, brightness in LIGHT.items():
        lines.append(f'    "{texture}_light": {" ".join(mask(jar, texture, brightness))!r},')
    for texture in METAL:
        for part, metal in (("metal", True), ("wood", False)):
            lines.append(f'    "{texture}_{part}": {" ".join(mask(jar, texture, metal=metal))!r},')
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUT} ({len(textures)} pictures, {len(LIGHT)} light masks, {len(METAL)} metal/wood splits)")


if __name__ == "__main__":
    main()
