import type { BrowserWindow } from 'electron'
import { app } from 'electron'
import { autoUpdater } from 'electron-updater'
import type { UpdateInfo } from 'electron-updater'
import { IpcChannel } from '../shared/ipc'
import type { UpdateStatus } from '../shared/types'

/** `UpdateInfo.releaseNotes` is `string | ReleaseNoteInfo[] | null` depending on whether
 * `autoUpdater.fullChangelog` is set (it isn't here, so this repo's GitHub provider always sends
 * a plain string in practice) - handled defensively either way rather than assuming. Typed off
 * `UpdateInfo['releaseNotes']` itself rather than importing `ReleaseNoteInfo` from
 * `builder-util-runtime` directly - that's only a transitive dependency of `electron-updater`, not
 * one of this project's own declared dependencies. */
function releaseNotesToString(notes: UpdateInfo['releaseNotes']): string | undefined {
  if (!notes) return undefined
  if (typeof notes === 'string') return notes
  return notes.map((entry) => entry.note ?? '').join('\n\n')
}

/**
 * Phase 9: real auto-update, replacing the old Phase 6d informational-only manifest check (see
 * `shared/types.ts`'s `UpdateStatus` doc comment). `electron-updater` checks this repo's GitHub
 * Releases directly - no more hand-maintained `update-manifest.json` to keep in sync with
 * `package.json`'s version by hand.
 *
 * Deliberately a no-op unless `app.isPackaged` - `electron-updater` expects a properly packaged,
 * versioned app (it looks for `app-update.yml`, generated by `electron-builder`, next to the
 * executable) and isn't meant to run against a dev build at all; every one of its own examples and
 * the library's own docs gate it the same way.
 */
export function registerAutoUpdater(window: BrowserWindow): void {
  if (!app.isPackaged) {
    return
  }

  const send = (status: UpdateStatus): void => {
    if (!window.isDestroyed()) {
      window.webContents.send(IpcChannel.UpdateStatus, status)
    }
  }

  autoUpdater.autoDownload = true
  autoUpdater.on('checking-for-update', () => send({ state: 'checking' }))
  autoUpdater.on('update-available', (info) => send({ state: 'available', version: info.version }))
  autoUpdater.on('update-not-available', () => send({ state: 'not-available' }))
  autoUpdater.on('download-progress', (info) => send({ state: 'downloading', percent: Math.round(info.percent) }))
  autoUpdater.on('update-downloaded', (info) =>
    send({ state: 'downloaded', version: info.version, releaseNotes: releaseNotesToString(info.releaseNotes) })
  )
  autoUpdater.on('error', (error) => send({ state: 'error', message: error.message }))

  void autoUpdater.checkForUpdates()
}

/** Quits and relaunches into the already-downloaded update - only meaningful after an
 * `update-downloaded` status, the renderer only ever offers this once that's happened. */
export function installUpdateNow(): void {
  autoUpdater.quitAndInstall()
}
