/** Channel names shared between main and preload/renderer, kept in one place so both sides
 * stay in sync (renaming a channel here is a compile error everywhere it's used). */
export const IpcChannel = {
  AuthRestore: 'auth:restore',
  AuthLogin: 'auth:login',
  AuthLoginMock: 'auth:login-mock',
  AuthProgress: 'auth:progress',
  AuthProfile: 'auth:profile',
  LaunchPlay: 'launch:play',
  LaunchProgress: 'launch:progress',
  VersionsList: 'versions:list',
  GameLog: 'game:log',
  ShellOpenExternal: 'shell:open-external',
  SettingsLoad: 'settings:load',
  SettingsSave: 'settings:save',
  ModsListBundled: 'mods:list-bundled',
  ModsListCustom: 'mods:list-custom',
  ModsAddCustom: 'mods:add-custom',
  ModsRemoveCustom: 'mods:remove-custom',
  InstancesDelete: 'instances:delete',
  UpdateStatus: 'update:status',
  UpdateInstallNow: 'update:install-now',
  SkinFetchTexture: 'skin:fetch-texture',
  SkinUpload: 'skin:upload',
  SkinEditorLoadPng: 'skin-editor:load-png',
  SkinEditorLoadTemplate: 'skin-editor:load-template',
  SkinEditorExportPng: 'skin-editor:export-png',
  SkinLibraryList: 'skin-library:list',
  SkinLibrarySave: 'skin-library:save',
  SkinLibraryDelete: 'skin-library:delete',
  SkinLibraryUse: 'skin-library:use',
  SkinLibraryLoadForEdit: 'skin-library:load-for-edit',
  SkinLibraryRename: 'skin-library:rename',
  StorageInfo: 'storage:info',
  StorageChangeLocation: 'storage:change-location',
  StorageMoveProgress: 'storage:move-progress'
} as const
