"""Writes third-party-licenses/npm-packages.txt: the license text of every npm package that ships
inside the packaged launcher (production dependencies only, transitive ones included).

Run from launcher/ after `npm install` whenever a dependency is added, removed or updated:
    python scripts/collect_npm_licenses.py
"""

import json
import os
import subprocess
import sys

LAUNCHER_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(LAUNCHER_DIR, "third-party-licenses", "npm-packages.txt")
LICENSE_PREFIXES = ("license", "licence", "copying")


def package_dirs():
    result = subprocess.run(
        "npm ls --omit=dev --all --parseable",
        cwd=LAUNCHER_DIR, capture_output=True, text=True, shell=True)
    dirs = {os.path.normpath(line.strip()) for line in result.stdout.splitlines() if line.strip()}
    dirs.discard(os.path.normpath(LAUNCHER_DIR))
    return dirs


def license_text(package_dir):
    for name in sorted(os.listdir(package_dir)):
        if name.lower().startswith(LICENSE_PREFIXES) and os.path.isfile(os.path.join(package_dir, name)):
            with open(os.path.join(package_dir, name), encoding="utf-8", errors="replace") as file:
                return file.read().strip()
    return None


def main():
    entries = []
    for package_dir in package_dirs():
        with open(os.path.join(package_dir, "package.json"), encoding="utf-8") as file:
            meta = json.load(file)
        entries.append((meta["name"], meta.get("version", "?"), meta.get("license", "unknown"), license_text(package_dir)))
    entries.sort(key=lambda entry: entry[0])

    missing = [name for name, _, _, text in entries if text is None]
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as out:
        out.write("npm packages shipped inside TNT's All-In-1 Client launcher\n")
        out.write("Generated by launcher/scripts/collect_npm_licenses.py - do not edit by hand.\n")
        for name, version, license_id, text in entries:
            out.write("\n" + "=" * 78 + "\n")
            out.write(f"{name} {version} - {license_id}\n")
            out.write("=" * 78 + "\n\n")
            out.write((text or f"No license file in the package; its package.json states: {license_id}") + "\n")

    print(f"Wrote {len(entries)} packages to {OUTPUT}")
    if missing:
        print("Without a license file (package.json license used instead): " + ", ".join(missing), file=sys.stderr)


if __name__ == "__main__":
    main()
